name: digitovsky

services:
  java:
    build: . #./backend
    # container_name: spring-digitovsky
    volumes:
      - ./digitovsky:/usr/local/service
    command: [ "sh", "-c", "cd /usr/local/service && gradle bootRun" ]
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-digitovsky:3306/digitovsky
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql-digitovsky
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: ./bancoDados/sql
        target: /docker-entrypoint-initdb.d/

  #react:
  #  build: ./frontend
  #  volumes:
  #  - ./digitovsky/frontend:/usr/local/frontend
  #  ports:
  #    - 3000:3000
  #  depends_on:
  #    - java
  #  container_name: react-digitovsky
  #  stdin_open: true
  #  tty: true
    