package br.ufv.digitovsky.digitovsky;

public class ControladoraTextoAux {
    // Esse é um valor de template com exatamente 500 bytes para testes no caso
    // de uso Jogar. Posteriormente, essa classe será a responsável por
    // recuperar os textos de verdade e fornecê-los para o jogo; por ora,
    // fique com esse maravilhoso texto estático
    private final String texto =
      "têiãN1 ácId)n2\\têsáapi9á à é è ã ~ - ^ ê é è ¨ ë"
    + "aêuCã1 átOêr)m2\\aênis9   à é è ã ~ - ^ ê é è ¨ ë"
    + "aêpT1ã áeNt)d2\\iêtáum 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêoNã1 átEs) 2\\Mêrábi 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "aêuGã1 áuE )l2\\aêeárat9á à é è ã ~ - ^ ê é è ¨ ë"
    + "aê Cã1 áoNs)c2\\têtáur 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "vêiVã1 áeRr) 2\\nêsál c9á à é è ã ~ - ^ ê é è ¨ ë"
    + "nêeCã1 á Eg)t2\\ êpáten9á à é è ã ~ - ^ ê é è ¨ ë"
    + "sêoLã1 álIc)t2\\uêián N9á à é è ã ~ - ^ ê é è ¨ ë"
    + "TêrIã1 ásTi)u2\\eêtáurp9á à é è ã ~ - ^ ê é è ¨ ë"
    + "LêeCã1 átUs)F2\\aêiális9á à é è ã ~ - ^ ê é è ¨ ë"
    + "CêuRã1 áaBi)u2\\rêAáugu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "VêaRã1 áiUs) 2\\Aêcáums9á à é è ã ~ - ^ ê é è ¨ ë"
    + "TêoRã1 áqUe)t2\\ êránar9á à é è ã ~ - ^ ê é è ¨ ë"
    + "PêrAã1 áeSe)t2\\ êaáuci9á à é è ã ~ - ^ ê é è ¨ ë"
    + "SêuSã1 ácIp)t2\\ êaáxim9á à é è ã ~ - ^ ê é è ¨ ë"
    + "FêuSã1 ácE )o2\\rêaá da9á à é è ã ~ - ^ ê é è ¨ ë"
    + "cêlAã1 ásS )a2\\cêAárcu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêeTã1 áuS.)p2\\hêsáell9á à é è ã ~ - ^ ê é è ¨ ë"
    + "rêiDã1 áiCu)u2\\sêSáene9á à é è ã ~ - ^ ê é è ¨ ë"
    + "iênCã1 áePt)s2\\.ênáec 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "aêuGã1 áuE )f2\\fêcáitu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "hêiMã1 áeNa)o2\\sêHáabi9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêaRã1 átUr)e2\\nê áVes9á à é è ã ~ - ^ ê é è ¨ ë"
    + ",ê iã1 ámPe)d2\\iêtá Sa9á à é è ã ~ - ^ ê é è ¨ ë"
    + "PêlAã1 átEa)T2\\oêqáuen9á à é è ã ~ - ^ ê é è ¨ ë"
    + "Aê eã1 áfFi)i2\\têrá Od9á à é è ã ~ - ^ ê é è ¨ ë"
    + "TêoRã1 átOr)A2\\mêtá Do9á à é è ã ~ - ^ ê é è ¨ ë"
    + ".ê Aã1 á ma)t2\\iê áDap9á à é è ã ~ - ^ ê é è ¨ ë"
    + "nêaMã1 á Mo)b2\\iêPáhas9á à é è ã ~ - ^ ê é è ¨ ë"
    + "rêuTã1 árUm)N2\\eêuáe v9á à é è ã ~ - ^ ê é è ¨ ë"
    + "hêaBã1 áiTa)s2\\eêAáuct9á à é è ã ~ - ^ ê é è ¨ ë"
    + "cêoNã1 ásEc)e2\\têrá Cu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "nêoSã1 átRa)M2\\aênáa, 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêeNã1 áaTi)u2\\sêSáem 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "dêiSã1 á cr)s2\\ êuáism9á à é è ã ~ - ^ ê é è ¨ ë"
    + "fêaUã1 ácIb)s2\\ êránar9á à é è ã ~ - ^ ê é è ¨ ë"
    + "FêeRã1 ámEn)u2\\mêPáort9á à é è ã ~ - ^ ê é è ¨ ë"
    + "NêeTã1 áuS )a2\\cêláisi9á à é è ã ~ - ^ ê é è ¨ ë"
    + "MêaEã1 ácEn)s2\\ êeámpe9á à é è ã ~ - ^ ê é è ¨ ë"
    + "IêmPã1 áeRd)e2\\têfáauc9á à é è ã ~ - ^ ê é è ¨ ë"
    + "iênTã1 áeGe) 2\\Aêtáent9á à é è ã ~ - ^ ê é è ¨ ë"
    + "dêaPã1 áiBu) 2\\Cêráabi9á à é è ã ~ - ^ ê é è ¨ ë"
    + "qêuIã1 ásQu) 2\\Têiásti9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêrAã1 áeSe)t2\\.êbáibe9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêaUã1 árIs)S2\\eê áEu,9á à é è ã ~ - ^ ê é è ¨ ë"
    + "aêuGã1 áuE )o2\\nêaálli9á à é è ã ~ - ^ ê é è ¨ ë"
    + "fêrIã1 ánGi)l2\\aêSáapi9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêeTã1 áuS )u2\\bêláia 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "eêgEã1 ásTa) 2\\Pêeátiu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêrAã1 áeSe)t2\\ êaássa9á à é è ã ~ - ^ ê é è ¨ ë"
    + "NêoNã1 á su)c2\\iêiát C9á à é è ã ~ - ^ ê é è ¨ ë"
    + "CêoNã1 áuBi) 2\\Sêlálic9á à é è ã ~ - ^ ê é è ¨ ë"
    + "SêoDã1 áaLe) 2\\Sêgáitt9á à é è ã ~ - ^ ê é è ¨ ë"
    + "CêlAã1 ásS )u2\\aê áLac9á à é è ã ~ - ^ ê é è ¨ ë"
    + "RêuTã1 árUm) 2\\Têmápus9á à é è ã ~ - ^ ê é è ¨ ë"
    + "NêeQã1 áuE ).2\\ êeác S9á à é è ã ~ - ^ ê é è ¨ ë"
    + "fêaCã1 áiLi)i2\\sê áIn 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêoNã1 átEs)M2\\aêtáis 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "dêiAã1 ám T)m2\\pêsá Au9á à é è ã ~ - ^ ê é è ¨ ë"
    + "eêlEã1 ámEn)u2\\mêOádio9á à é è ã ~ - ^ ê é è ¨ ë"
    + ".ê Sã1 áaGi)t2\\iê áNul9á à é è ã ~ - ^ ê é è ¨ ë"
    + "qêuIã1 ásQu) 2\\Cênáubi9á à é è ã ~ - ^ ê é è ¨ ë"
    + "fêuSã1 ácE )e2\\uêiáat 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "eêgEã1 át S)e2\\lêráisq9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêaLã1 áeSu)d2\\aêNáam 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "aêd ã1 áMAt)i2\\sêUát f9á à é è ã ~ - ^ ê é è ¨ ë"
    + "lêiBã1 áeRo)E2\\xêPáhas9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêlAã1 átEa)N2\\oêtára 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêaLã1 áeSu)d2\\aêAáene9á à é è ã ~ - ^ ê é è ¨ ë"
    + "lêeOã1 á ut)E2\\fêiácit9á à é è ã ~ - ^ ê é è ¨ ë"
    + "lêoBã1 áoRt)s2\\ êlátri9á à é è ã ~ - ^ ê é è ¨ ë"
    + "fêaCã1 áiLi)i2\\sêMáoll9á à é è ã ~ - ^ ê é è ¨ ë"
    + "IêpSã1 áuM )i2\\sêsá Si9á à é è ã ~ - ^ ê é è ¨ ë"
    + "MêaEã1 ácEn)s2\\ êoándi9á à é è ã ~ - ^ ê é è ¨ ë"
    + "SêuSã1 ápEn)i2\\sêeá, V9á à é è ã ~ - ^ ê é è ¨ ë"
    + "PêhAã1 árEt)a2\\ êeátus9á à é è ã ~ - ^ ê é è ¨ ë"
    + "Eêu ã1 áFEl)s2\\ êuái E9á à é è ã ~ - ^ ê é è ¨ ë"
    + "QêuAã1 ám L)b2\\oêtáis 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "AêeNã1 áeAn)P2\\rêeásen9á à é è ã ~ - ^ ê é è ¨ ë"
    + ".ê Pã1 árEt)u2\\mêPáena9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêoSã1 áuEr) 2\\vênáena9á à é è ã ~ - ^ ê é è ¨ ë"
    + "lêaCã1 áuS )n2\\têrádum9á à é è ã ~ - ^ ê é è ¨ ë"
    + "eêuIã1 ásMo) 2\\Eêiát S9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêlAã1 átEa)P2\\hêráetr9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêoLã1 áeSt)e2\\ êeárme9á à é è ã ~ - ^ ê é è ¨ ë"
    + "nêeTã1 áuS )i2\\vêmáus 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "eêfFã1 áiCi)u2\\rêMáaxi9á à é è ã ~ - ^ ê é è ¨ ë"
    + "iêmPã1 áeRd)e2\\têSáit 9á à é è ã ~ - ^ ê é è ¨ ë"
    + ".ê Vã1 áeHi)u2\\lê áViv9á à é è ã ~ - ^ ê é è ¨ ë"
    + "hêaBã1 áiTa)s2\\eê áCla9á à é è ã ~ - ^ ê é è ¨ ë"
    + "SêaGã1 áiTt)s2\\ êuálpu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "OêrNã1 áaRe) 2\\jêsáto 9á à é è ã ~ - ^ ê é è ¨ ë"
    + ",ê mã1 áaTt)s2\\ êláass9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêrOã1 áiN )o2\\mêoádo 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "nêiBã1 áh S)t2\\ êrána 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "sêoCã1 áiOs)u2\\ êláand9á à é è ã ~ - ^ ê é è ¨ ë"
    + "nêiSã1 ál C)n2\\vêlális9á à é è ã ~ - ^ ê é è ¨ ë"
    + "uêrNã1 áa N)s2\\têaá Qu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "aêuGã1 áuE )u2\\rêeá Ia9á à é è ã ~ - ^ ê é è ¨ ë"
    + "DêoNã1 áeC )a2\\xêmáus 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "NêeQã1 áuE )e2\\lêtá Du9á à é è ã ~ - ^ ê é è ¨ ë"
    + ",ê mã1 áaSs) 2\\aêcáums9á à é è ã ~ - ^ ê é è ¨ ë"
    + "cêoNã1 ágUe) 2\\Eê áame9á à é è ã ~ - ^ ê é è ¨ ë"
    + ".ê Uã1 álTr)c2\\eê áVar9á à é è ã ~ - ^ ê é è ¨ ë"
    + ",ê dã1 áoNe) 2\\Lêcátus9á à é è ã ~ - ^ ê é è ¨ ë"
    + "lêoBã1 áoRt)s2\\ êiási 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêuLã1 ávIn)r2\\ êeándr9á à é è ã ~ - ^ ê é è ¨ ë"
    + "dêiCã1 átUm)m2\\aênáa, 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêaLã1 áeSu)d2\\aêaánte9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêrEã1 átIu) 2\\hêcá po9á à é è ã ~ - ^ ê é è ¨ ë"
    + "nêiSã1 ái v)s2\\têbáulu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "vêeLã1 á Vi)a2\\eênáequ9á à é è ã ~ - ^ ê é è ¨ ë"
    + "aêuGã1 áuE )o2\\sêráa c9á à é è ã ~ - ^ ê é è ¨ ë"
    + "nêeQã1 áuE )e2\\mêuás s9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêlAã1 ácEr)t2\\,êmáagn9á à é è ã ~ - ^ ê é è ¨ ë"
    + "eêsTã1 á. S)t2\\ êoámmo9á à é è ã ~ - ^ ê é è ¨ ë"
    + "sêaGã1 áiTt)s2\\,êtáemp9á à é è ã ~ - ^ ê é è ¨ ë"
    + "dêaPã1 áiBu) 2\\pêtáent9á à é è ã ~ - ^ ê é è ¨ ë"
    + "eêrAã1 át e)o2\\sêaánte9á à é è ã ~ - ^ ê é è ¨ ë"
    + "nêeQã1 áuE )e2\\lêeánte9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêoLã1 álIs)i2\\nêláuct9á à é è ã ~ - ^ ê é è ¨ ë"
    + "dêuIã1 ás m)r2\\bê ánat9á à é è ã ~ - ^ ê é è ¨ ë"
    + "sêuSã1 ápEn)i2\\sêeá. T9á à é è ã ~ - ^ ê é è ¨ ë"
    + "têoRã1 átOr)f2\\aêeás, 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "vêeSã1 átIb)l2\\uê ámon9á à é è ã ~ - ^ ê é è ¨ ë"
    + "aêd.ã1 á co)s2\\eêtáetu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "oêrCã1 ái e) 2\\fêiángi9á à é è ã ~ - ^ ê é è ¨ ë"
    + "eêu ã1 ádIa) 2\\dêsá in9á à é è ã ~ - ^ ê é è ¨ ë"
    + "sêoCã1 áiOs)u2\\ êoártt9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêaGã1 ánIs)a2\\uêtáor,9á à é è ã ~ - ^ ê é è ¨ ë"
    + ",ê Nã1 áiSl)s2\\eê ánat9á à é è ã ~ - ^ ê é è ¨ ë"
    + "fêaCã1 áiLi)i2\\ êláand9á à é è ã ~ - ^ ê é è ¨ ë"
    + "uêlLã1 áaMc)r2\\pêrá in9á à é è ã ~ - ^ ê é è ¨ ë"
    + "cêrAã1 ás p)r2\\tê ános9á à é è ã ~ - ^ ê é è ¨ ë"
    + "sêoLã1 álIc)t2\\uêián l9á à é è ã ~ - ^ ê é è ¨ ë"
    + "sêeMã1 á Fe)m2\\eêtáum 9á à é è ã ~ - ^ ê é è ¨ ë"
    + ",ê Mã1 áaUr)s2\\ êoástr9á à é è ã ~ - ^ ê é è ¨ ë"
    + "SêuSã1 ápEn)i2\\sêeá eg9á à é è ã ~ - ^ ê é è ¨ ë"
    + "lêeCã1 átUs)s2\\oêiáosq9á à é è ã ~ - ^ ê é è ¨ ë"
    + "nêuLã1 álAm)p2\\rêmáis 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêaRã1 átUr)e2\\nê ápro9á à é è ã ~ - ^ ê é è ¨ ë"
    + "fêiNã1 áiBu) 2\\pêaásel9á à é è ã ~ - ^ ê é è ¨ ë"
    + "dêiCã1 átUm)t2\\.êAá cu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "têrIã1 ásTi)u2\\eêdáign9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêoNã1 átEs)m2\\iêuát q9á à é è ã ~ - ^ ê é è ¨ ë"
    + "iênCã1 áePt)s2\\ êeátus9á à é è ã ~ - ^ ê é è ¨ ë"
    + "FêaCã1 áiLi)i2\\ êeátus9á à é è ã ~ - ^ ê é è ¨ ë"
    + "lêoRã1 áeM )h2\\oêcáus 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "oêdIã1 áo a)c2\\uêláaci9á à é è ã ~ - ^ ê é è ¨ ë"
    + ",ê Sã1 áeNe)t2\\uê ácla9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêeLã1 álEn)e2\\sêuáe q9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêaRã1 átUr)e2\\nê áera9á à é è ã ~ - ^ ê é è ¨ ë"
    + "iên ã1 árIs)s2\\ êuábil9á à é è ã ~ - ^ ê é è ¨ ë"
    + "sêiTã1 á La)i2\\nêaá ma9á à é è ã ~ - ^ ê é è ¨ ë"
    + "iêaCã1 áuLi) 2\\eêoás p9á à é è ã ~ - ^ ê é è ¨ ë"
    + "eêlEã1 áiFe)d2\\ êiási 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "cêuRã1 ásUs)n2\\aêoáque9á à é è ã ~ - ^ ê é è ¨ ë"
    + "oêdIã1 áo l)c2\\uê áaen9á à é è ã ~ - ^ ê é è ¨ ë"
    + "nêeQã1 áuE )s2\\têbáibe9á à é è ã ~ - ^ ê é è ¨ ë"
    + "uêlTã1 árIc)s2\\ êoártt9á à é è ã ~ - ^ ê é è ¨ ë"
    + "eêlEã1 áiFe)d2\\ êcá hi9á à é è ã ~ - ^ ê é è ¨ ë"
    + "fêeRã1 ámEn)u2\\mêsáit.9á à é è ã ~ - ^ ê é è ¨ ë"
    + "cêlAã1 ásS )t2\\ êiágni9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêaGã1 ánIs)m2\\uê áege9á à é è ã ~ - ^ ê é è ¨ ë"
    + "aê Mã1 áaUr)s2\\ êeándr9á à é è ã ~ - ^ ê é è ¨ ë"
    + "Aê Mã1 áaEc)n2\\aê áinc9á à é è ã ~ - ^ ê é è ¨ ë"
    + "eêlEã1 ámEn)u2\\mêsáusc9á à é è ã ~ - ^ ê é è ¨ ë"
    + "rêiDã1 áiCu)u2\\sêláigu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "têoRã1 áqUe)t2\\ êeátus9á à é è ã ~ - ^ ê é è ¨ ë"
    + "cêoNã1 áuBi) 2\\mêrábi 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "eêlEã1 áiFe)d2\\ êuáism9á à é è ã ~ - ^ ê é è ¨ ë"
    + ",ê Mã1 áaUr)s2\\ êlátri9á à é è ã ~ - ^ ê é è ¨ ë"
    + "nêoSã1 átRa) 2\\Aênáean9á à é è ã ~ - ^ ê é è ¨ ë"
    + "têeMã1 ápOr)s2\\oêláici9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêaSã1 ásA )d2\\ êuálla9á à é è ã ~ - ^ ê é è ¨ ë"
    + ",ê Nã1 áaM )e2\\cêbáibe9á à é è ã ~ - ^ ê é è ¨ ë"
    + "iênCã1 áePt)s2\\ êeáhic9á à é è ã ~ - ^ ê é è ¨ ë"
    + "aêd ã1 ásAg)t2\\têsá ne9á à é è ã ~ - ^ ê é è ¨ ë"
    + "sêcEã1 álEr)s2\\qêeá ma9á à é è ã ~ - ^ ê é è ¨ ë"
    + "iênTã1 áeRd)m2\\ êaác d9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêlAã1 ácEr)t2\\ êoádal9á à é è ã ~ - ^ ê é è ¨ ë"
    + "dêiCã1 átUm)t2\\,êláito9á à é è ã ~ - ^ ê é è ¨ ë"
    + "eêgEã1 át t)l2\\lêsá qu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "aê Pã1 áeR,)f2\\uêcáe p9á à é è ã ~ - ^ ê é è ¨ ë"
    + "AêrCã1 áu n)b2\\hêváeli9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêrIã1 ámIs)m2\\eêuás s9á à é è ã ~ - ^ ê é è ¨ ë"
    + "aêpTã1 áeNt)s2\\aêiátti9á à é è ã ~ - ^ ê é è ¨ ë"
    + "rêiDã1 áiCu)u2\\sêfáeug9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêoLã1 áeSt)e2\\ ênácep9á à é è ã ~ - ^ ê é è ¨ ë"
    + "cêoNã1 áuBi) 2\\aêcáums9á à é è ã ~ - ^ ê é è ¨ ë"
    + "sêaPã1 áiEn)n2\\iêlá. N9á à é è ã ~ - ^ ê é è ¨ ë"
    + "têeMã1 ápOr) 2\\rêtárum9á à é è ã ~ - ^ ê é è ¨ ë"
    + ",ê Pã1 áuLv)n2\\aê ápha9á à é è ã ~ - ^ ê é è ¨ ë"
    + "cêuRã1 áaBi)u2\\rêpároi9á à é è ã ~ - ^ ê é è ¨ ë"
    + "nêaSã1 ácEt)r2\\,êsáit 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "fêiNã1 áiBu) 2\\aêcáu p9á à é è ã ~ - ^ ê é è ¨ ë"
    + "cêuRã1 áaE )o2\\rêuáent9á à é è ã ~ - ^ ê é è ¨ ë"
    + "têrIã1 ásTi)u2\\eêváel 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "sêoCã1 áiOs)u2\\ êcácum9á à é è ã ~ - ^ ê é è ¨ ë"
    + "lêeOã1 á Li)o2\\rê áfer9á à é è ã ~ - ^ ê é è ¨ ë"
    + "TêaCã1 áiTi)p2\\lêtáea 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "dêêiCã1 átUm)t2\\ êi;t,]9 à é è ã ~ - ^ ê é è ¨ ë"
    + "sêeDã1 á Ri)i2\\cêláus 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "sêoDã1 áaLe) 2\\vêháicu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "jêuSã1 átO )a2\\gêaá eg9á à é è ã ~ - ^ ê é è ¨ ë"
    + ",ê Aã1 ámEt)p2\\rêmáis 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "cêuRã1 áaE.)I2\\nêeáger9á à é è ã ~ - ^ ê é è ¨ ë"
    + "dêoNã1 áeC )i2\\sêsá di9á à é è ã ~ - ^ ê é è ¨ ë"
    + "vêeNã1 áeNa)i2\\sêiámpe9á à é è ã ~ - ^ ê é è ¨ ë"
    + "nêaSã1 ácEt)r2\\ êtá ut9á à é è ã ~ - ^ ê é è ¨ ë"
    + "lêoRã1 áeM )p2\\sêmá ex9á à é è ã ~ - ^ ê é è ¨ ë"
    + "cêoNã1 ágUe)n2\\aêoáque9á à é è ã ~ - ^ ê é è ¨ ë"
    + "lêaOã1 árEe) 2\\pêrá do9á à é è ã ~ - ^ ê é è ¨ ë"
    + "sêoCã1 áiOs)u2\\ êráavi9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêeLã1 álEn)e2\\sêuáe n9á à é è ã ~ - ^ ê é è ¨ ë"
    + "hêaBã1 áiTa)s2\\eêeást 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "nêaSã1 ácEt)r2\\ êháare9á à é è ã ~ - ^ ê é è ¨ ë"
    + "dêoLã1 áoR )i2\\sê ádap9á à é è ã ~ - ^ ê é è ¨ ë"
    + "lêaOã1 árEe) 2\\sêsápen9á à é è ã ~ - ^ ê é è ¨ ë"
    + "aêuGã1 áuE )m2\\pêrádie9á à é è ã ~ - ^ ê é è ¨ ë"
    + "uêlLã1 áaMc)r2\\pêrá di9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêuLã1 ávIn)r2\\,êsáed 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêrIã1 ámIs) 2\\Hêmáena9á à é è ã ~ - ^ ê é è ¨ ë"
    + "vêuLã1 ápUt)t2\\eê álig9á à é è ã ~ - ^ ê é è ¨ ë"
    + ",ê Lã1 áoBo)t2\\iê ámat9á à é è ã ~ - ^ ê é è ¨ ë"
    + "dêuIã1 á In)e2\\pêoás t9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêoTã1 áeNt) 2\\sêeáler9á à é è ã ~ - ^ ê é è ¨ ë"
    + "jêuSã1 átO )r2\\iêgáill9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêaSã1 ásA )x2\\ êdáipi9á à é è ã ~ - ^ ê é è ¨ ë"
    + "fêaCã1 áiLi)i2\\sêcáomm9á à é è ã ~ - ^ ê é è ¨ ë"
    + "vêeLã1 á Du) 2\\mêeácen9á à é è ã ~ - ^ ê é è ¨ ë"
    + "fêrIã1 ánGi)l2\\aêiápsu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "oêrNã1 áaRe)m2\\aêsáa, 9á à é è ã ~ - ^ ê é è ¨ ë"
    + ".ê oã1 árNa)e2\\ êoácio9á à é è ã ~ - ^ ê é è ¨ ë"
    + "lêiGã1 áuLa) 2\\lêráem 9á à é è ã ~ - ^ ê é è ¨ ë"
    + ",ê Gã1 árAv)d2\\aêtáell9á à é è ã ~ - ^ ê é è ¨ ë"
    + "CêoNã1 ávAl)i2\\sêmáus 9á à é è ã ~ - ^ ê é è ¨ ë"
    + ",ê Cã1 áuBi)i2\\aêoárna9á à é è ã ~ - ^ ê é è ¨ ë"
    + ",ê Lã1 áoRe) 2\\qêaám v9á à é è ã ~ - ^ ê é è ¨ ë"
    + "GêrAã1 ávId) 2\\nêtáoqu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "sêaGã1 áiTt)s2\\ êiáctu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêoRã1 átTi)o2\\rênáull9á à é è ã ~ - ^ ê é è ¨ ë"
    + "cêoNã1 ásEc)e2\\têrá lu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "SêoLã1 álIc)t2\\uêián q9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêaTã1 átIs)a2\\uêtáor 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "sêeMã1 ápEr)p2\\uêuás v9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêaRã1 átUr)e2\\nê áneq9á à é è ã ~ - ^ ê é è ¨ ë"
    + "bêiBã1 áeNd)m2\\,êfáaci9á à é è ã ~ - ^ ê é è ¨ ë"
    + "fêeLã1 áiS )u2\\cêuás e9á à é è ã ~ - ^ ê é è ¨ ë"
    + "iêaCã1 áuLi) 2\\fêmáes 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "eêlEã1 ámEn)u2\\mêtáell9á à é è ã ~ - ^ ê é è ¨ ë"
    + "dêiSã1 á Li)o2\\rê áarc9á à é è ã ~ - ^ ê é è ¨ ë"
    + "nêiSã1 ál f)s2\\cê ámal9á à é è ã ~ - ^ ê é è ¨ ë"
    + ",ê Mã1 áuS )u2\\iêváiva9á à é è ã ~ - ^ ê é è ¨ ë"
    + "uêlTã1 árIc)e2\\sêeást,9á à é è ã ~ - ^ ê é è ¨ ë"
    + "vêeLã1 áiT )t2\\iêmá bi9á à é è ã ~ - ^ ê é è ¨ ë"
    + "dêiCã1 átUm)t2\\ êdá su9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêoLã1 álIs)a2\\dêpáisc9á à é è ã ~ - ^ ê é è ¨ ë"
    + "hêiMã1 áeNa)o2\\sêiánte9á à é è ã ~ - ^ ê é è ¨ ë"
    + "gêrAã1 ávId) 2\\fêrámen9á à é è ã ~ - ^ ê é è ¨ ë"
    + "sêoLã1 álIc)t2\\uêián q9á à é è ã ~ - ^ ê é è ¨ ë"
    + ",ê Tã1 áeLl)s2\\ êcáele9á à é è ã ~ - ^ ê é è ¨ ë"
    + "têoRã1 áqUe)t2\\.êJáust9á à é è ã ~ - ^ ê é è ¨ ë"
    + "dêiAã1 ám r)s2\\uê,á ma9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêaLã1 áeSu)d2\\aê ásus9á à é è ã ~ - ^ ê é è ¨ ë"
    + ".ê pã1 áaRt)r2\\iênát p9á à é è ã ~ - ^ ê é è ¨ ë"
    + "lêiGã1 áuLa)m2\\aêtáis 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "pêrAã1 áeSe)t2\\ êfáfic9á à é è ã ~ - ^ ê é è ¨ ë"
    + "dêiAã1 ám s)s2\\cêpáit 9á à é è ã ~ - ^ ê é è ¨ ë"
    + "hêaBã1 áiTa)s2\\eê áDis9á à é è ã ~ - ^ ê é è ¨ ë"
    + "nêoSã1 átRa)p2\\eê,á nu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêi,ã1 á Ul)r2\\iêeás f9á à é è ã ~ - ^ ê é è ¨ ë"
    + ".ê nã1 áuLl) 2\\nêcá li9á à é è ã ~ - ^ ê é è ¨ ë"
    + "lêaCã1 áiNi) 2\\mêláest9á à é è ã ~ - ^ ê é è ¨ ë"
    + "aêc ã1 áeLe)e2\\nêuám t9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêaEã1 ácEn)s2\\ êiágni9á à é è ã ~ - ^ ê é è ¨ ë"
    + "fêeRã1 ámEn)u2\\mêmáaec9á à é è ã ~ - ^ ê é è ¨ ë"
    + "lêiTã1 áoRa)i2\\nêoádio9á à é è ã ~ - ^ ê é è ¨ ë"
    + "cêoNã1 ádIm)n2\\têmá el9á à é è ã ~ - ^ ê é è ¨ ë"
    + "dêaPã1 áiBu) 2\\cêráabi9á à é è ã ~ - ^ ê é è ¨ ë"
    + "dêoLã1 áoR )e2\\lêuás p9á à é è ã ~ - ^ ê é è ¨ ë"
    + "vêeLã1 áiT )e2\\nêcátus9á à é è ã ~ - ^ ê é è ¨ ë"
    + "mêaTã1 átIs)m2\\iêiáacu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "cêuRã1 áaBi)u2\\rêláacu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "têaCã1 áiTi)n2\\iêiá cu9á à é è ã ~ - ^ ê é è ¨ ë"
    + "nêuLã1 álA )g2\\eê ápha9á à é è ã ~ - ^ ê é è ¨ ë";

    private final String texto2 = "Enquanto passa preguiçosamente o tempo com "
    + "sua irmã, Alice vê o Coelho Branco de colete, "
    + "carregando um relógio de bolso."
    + "sua irmã, Alice vê o Coelho Branco de colete, "
    + "carregando um relógio de bolso."
    + "sua irmã, Alice vê o Coelho Branco de colete, "
    + "carregando um relógio de bolso."
    + "sua irmã, Alice vê o Coelho Branco de colete, "
    + "carregando um relógio de bolso."
    + "sua irmã, Alice vê o Coelho Branco de colete, "
    + "carregando um relógio de bolso."
    + "sua irmã, Alice vê o Coelho Branco de colete, "
    + "carregando um relógio de bolso."
    + "sua irmã, Alice vê o Coelho Branco de colete, "
    + "carregando um relógio de bolso.";
    public String getTexto() {
        return texto2;
    }
}
