-- Banco teste
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `digitovsky` DEFAULT CHARACTER SET utf8 ;
USE `digitovsky`;

CREATE TABLE IF NOT EXISTS `digitovsky`.`TB_teste` (
  `PK_duduAntunesS2` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `apelido` VARCHAR(15) NULL,
  PRIMARY KEY (`PK_duduAntunesS2`),
  UNIQUE INDEX `PK_duduAntunesS2_UNIQUE` (`PK_duduAntunesS2` ASC))
ENGINE = InnoDB;

INSERT INTO TB_teste (apelido) VALUES ('Eduardo');
INSERT INTO TB_teste (apelido) VALUES ('Bradas');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
